{
  assertThat(exception,is(Matchers.<Object>instanceOf(RemoteAccessException.class)));
  assertThat(exception.getCause(),sameInstance((Throwable)innerException));
}
