{
  try {
    new Tasks().incrementIndex(1);
    fail("Should have thrown up");
  }
 catch (  Exception e) {
    assertThat(e.getMessage(),is("There is not valid task at position 1."));
  }
}
